# Heart Disease Prediction using Machine Learning

The data set is obtained from Kaggle. It has patient records with 13 parameters and last column contains wether the patient has heart disease or not.

### Importing Libraries and reading the dataset

In [1]:
import pandas as pd
from sklearn import neighbors,metrics
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import numpy as np
import pickle
from sklearn.ensemble import RandomForestClassifier
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [2]:
heart_df = pd.read_csv('heart.csv')

In [3]:
heart_df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [4]:
heart_df.astype({'oldpeak':'int64'}).dtypes

age         int64
sex         int64
cp          int64
trestbps    int64
chol        int64
fbs         int64
restecg     int64
thalach     int64
exang       int64
oldpeak     int64
slope       int64
ca          int64
thal        int64
target      int64
dtype: object

### Dividing the dataset into train and test set

In [5]:
X = heart_df[['age','sex','cp','trestbps','chol','fbs','restecg','thalach','exang','oldpeak','slope','ca','thal']].values

In [6]:
y = heart_df[['target']].values

In [7]:
X

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [8]:
y = y.flatten()
print(y)

[0 0 0 ... 0 1 0]


### KNN Model

In [9]:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=4)

In [10]:
    knn = KNeighborsClassifier(n_neighbors = 20)
    knn.fit(X_train, y_train)
    print(knn.score(X_test, y_test))

0.7121951219512195


In [11]:
pickle.dump(knn,open('heart_knn_model.sav','wb'))

In [12]:
predict_knn = knn.predict(X_test)
accuracy_knn  = metrics.accuracy_score(y_test,predict_knn)

In [13]:
predict_knn

array([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0], dtype=int64)

In [14]:
accuracy_knn

0.7121951219512195

### Decision Trees Model

In [15]:
clf = DecisionTreeClassifier(random_state=2)
clf.fit(X_train,y_train)

DecisionTreeClassifier(random_state=2)

In [16]:
prediction_dtree = clf.predict(X_test)
accuracy_dtree = metrics.accuracy_score(y_test,prediction_dtree)

In [17]:
print(prediction_dtree)

[1 1 1 0 1 1 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0 0 1 0
 1 1 0 1 1 1 1 1 0 1 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 0 1 1 1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 0 0 0 0 1 0 1 0 0 0 1 0 1 1 0 1 1
 0 1 0 0 1 1 0 0 1 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0
 0 0 1 0 0 1 1 0 1 0 0 0 0 1 1 0 1 1 1 1 1 0 1 1 1 1 0 0 0 0 1 0 0 0 0 0 0
 0 1 1 0 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 0]


In [18]:
print(accuracy_dtree)

1.0


In [19]:
pickle.dump(clf,open('heart_dt_model.sav','wb'))

In [20]:
clf = pickle.load(open('heart_dt_model.sav','rb'))

In [21]:
input = [[63,1,3,145,233,1,0,150,0,2.3,0,0,1]]
p = clf.predict(input)
print(p)

[1]


### Random Forest Model

In [22]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)

RandomForestClassifier()

In [23]:
predict_rf = rf.predict_proba(X_test)
predict_rf

array([[0.03, 0.97],
       [0.03, 0.97],
       [0.33, 0.67],
       [0.98, 0.02],
       [0.01, 0.99],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.99, 0.01],
       [0.03, 0.97],
       [0.13, 0.87],
       [0.  , 1.  ],
       [0.03, 0.97],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.02, 0.98],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.97, 0.03],
       [0.97, 0.03],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.04, 0.96],
       [0.1 , 0.9 ],
       [0.03, 0.97],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.87, 0.13],
       [0.06, 0.94],
       [0.04, 0.96],
       [0.05, 0.95],
       [1.  , 0.  ],
       [0.11, 0.89],
       [0.92, 0.08],
       [0.99, 0.01],
       [0.99, 0.01],
       [0.1 , 0.9 ],
       [0.97, 0.03],
       [0.  , 1.  ],
       [0.02, 0.98],
       [0.94, 0.06],
       [0.  , 1.  ],
       [0.06, 0.94],
       [0.08, 0.92],
       [0.  , 1.  ],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.05, 0.95],
       [0.01,

In [24]:
pickle.dump(clf,open('heart_rt_model.pkl','wb'))
clf = pickle.load(open('heart_rt_model.pkl','rb'))

In [25]:
import joblib

In [26]:
joblib.dump(rf,'heart_rf_model.sav')

['heart_rf_model.sav']

In [27]:
model = joblib.load('heart_rf_model.sav')

In [28]:
model.predict_proba(X_test)

array([[0.03, 0.97],
       [0.03, 0.97],
       [0.33, 0.67],
       [0.98, 0.02],
       [0.01, 0.99],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.99, 0.01],
       [0.03, 0.97],
       [0.13, 0.87],
       [0.  , 1.  ],
       [0.03, 0.97],
       [0.  , 1.  ],
       [0.  , 1.  ],
       [0.02, 0.98],
       [0.99, 0.01],
       [1.  , 0.  ],
       [0.97, 0.03],
       [0.97, 0.03],
       [1.  , 0.  ],
       [0.  , 1.  ],
       [0.04, 0.96],
       [0.1 , 0.9 ],
       [0.03, 0.97],
       [0.  , 1.  ],
       [1.  , 0.  ],
       [0.87, 0.13],
       [0.06, 0.94],
       [0.04, 0.96],
       [0.05, 0.95],
       [1.  , 0.  ],
       [0.11, 0.89],
       [0.92, 0.08],
       [0.99, 0.01],
       [0.99, 0.01],
       [0.1 , 0.9 ],
       [0.97, 0.03],
       [0.  , 1.  ],
       [0.02, 0.98],
       [0.94, 0.06],
       [0.  , 1.  ],
       [0.06, 0.94],
       [0.08, 0.92],
       [0.  , 1.  ],
       [0.01, 0.99],
       [1.  , 0.  ],
       [0.05, 0.95],
       [0.01,